name = "hole"
author = "suvi"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e3964d892a93131b56b2dda3270f4de68556f72cfebc36c6e01965a7e906ec3"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
