name = "hole"
author = "suvi"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41ce0072faf8e85f19d250533e5bae2cde46848246504d26377cb841c907c80a"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
